#cache:
#    algorithm: LRU
#    maxSize: 100
#spring:
#    datasource:
#        url: jdbc:postgresql://localhost:5432/entity
#        username: postgres
#        password: sa
#        driver-class-name: org.postgresql.Driver
#    jpa:
#        database-platform: org.hibernate.dialect.PostgreSQLDialect
#        show-sql: true
#        hibernate:
#            ddl-auto: update
#    mvc:
#        hiddenmethod:
#            filter:
#                enabled: true
database:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/entity
    user: postgres
    password: sa
    min: 2
    max: 100
    autocommit: true
    auto_init: true
    add_data: true
    sql:
        schema: sql/schema.sql
        data: sql/data.sql
        drop: sql/drop.sql
cache:
    type: LRU
    size: 100